# Generated by Django 5.0.3 on 2024-03-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_alumno_profesor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='camada_alumno',
            new_name='camada',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='nombre_alumno',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='camada_profesor',
            new_name='camada',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='nombre_profesor',
            new_name='nombre',
        ),
    ]
